ED2_Lab1/ED2_Lab1/Models/LZW.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace ED2_Lab1.Models
{
    public class LZW
    {
        public  List<int> Compresion(string Descomprimido)
        {
            // Crando Diccionario
            List<int> indices = new List<int>();
            Dictionary<int, string> dictionary = new Dictionary<int, string>();

            for (int i = 0; i < 256; i++)
                dictionary.Add(i, new string((char)i, 1));

            char c = '\0';
            int index = 1, n = Descomprimido.Length, nextKey = 256;
            string s = new string(Descomprimido[0], 1), sc = string.Empty;

            while (index < n)
            {
                c = Descomprimido[index++];
                sc = s + c;

                if (dictionary.ContainsValue(sc))
                    s = sc;

                else
                {
                    foreach (KeyValuePair<int, string> kvp in dictionary)
                    {
                        if (kvp.Value == s)
                        {
                            indices.Add(kvp.Key);
                            break;
                        }
                    }

                    dictionary.Add(nextKey++, sc);
                    s = new string(c, 1);
                }
            }

            foreach (KeyValuePair<int, string> kvp in dictionary)
            {
                if (kvp.Value == s)
                {
                    indices.Add(kvp.Key);
                    break;
                }
            }

            return indices;
        }

        public string Descompresion(List<int> Comprimido)
        {
            // Crando Diccionario
            Dictionary<int, string> Diccionario = new Dictionary<int, string>();
            for (int i = 0; i < 256; i++)
                Diccionario.Add(i, ((char)i).ToString());

            string w = Diccionario[Comprimido[0]];
            Comprimido.RemoveAt(0);
            StringBuilder Descomprimido = new StringBuilder(w);

            foreach (int k in Comprimido)
            {
                string entry = null;
                if (Diccionario.ContainsKey(k))
                    entry = Diccionario[k];
                else if (k == Diccionario.Count)
                    entry = w + w[0];

                Descomprimido.Append(entry);

                // Agregando al diccionario la entrada
                Diccionario.Add(Diccionario.Count, w + entry[0]);
                w = entry;
            }

            return Descomprimido.ToString();
        }

    }
}

ED2_Lab1/ED2_Lab1/Controllers/LZWController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ED2_Lab1.Models;
using System.Web.Mvc;
using System.IO;
using ED2_Lab1.Models;
using ED2_Lab1.DBContext;
using System.Text;
using ED2_Lab1.Compresion;

namespace ED2_Lab1.Controllers
{
    public class LZWController : Controller
    {
        public DefaultConnectionLZW db = DefaultConnectionLZW.getInstance;
        LZW algoritmo = new LZW();
        static LogFile log = new LogFile();

        //HOME DE LZW
        public ActionResult Index()
        {
            //List<int> compreso = algoritmo.Compresion("HOLACOMOESTASMAJE");
            //string descompreso = algoritmo.Descompresion(compreso);
            return View(db.ObtenerHistorial());
        }

        //COMPRESION DE ARCHIVO 
        [HttpGet]
        public ActionResult CompressFile()
        {
            return View();
        }
        //COMPRESION DE ARCHIVO 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CompressFile(HttpPostedFileBase File)
        {
            string filePath = string.Empty;
            if (File != null)
            {
                string path = Server.MapPath("~/UploadedFiles/");
                filePath = path + Path.GetFileName(File.FileName);
                string extension = Path.GetExtension(File.FileName);
                File.SaveAs(filePath);
                ViewBag.Message = "Archivo Cargado";

                FileInfo fileInfo = new FileInfo(filePath);

                string nombre_original = fileInfo.Name;
                long tamanio_original = fileInfo.Length;

                db.GuardarArchivo(fileInfo);
                GenerarArhivoComprimido();
                //db.GuardarArchivo(fileInfo);
                //DownloadFile(fileInfo);

                
                log.GenerarLog(nombre_original, tamanio_original, db.ObtenerArchivo().Length);
                db.GuardarHistorial(log.ListaHistorial);

                return RedirectToAction("DownloadFile");
            }

            return View();
        }

        public void GenerarArhivoComprimido()
        {
            const int bufferLength = 100;
            List<int> bytedecompress = new List<int>();
            StringBuilder builder = new StringBuilder();

            var buffer = new byte[bufferLength];
            using (var file = new FileStream(db.ObtenerArchivo().FullName, FileMode.Open))
            {
                using (var reader = new BinaryReader(file))
                {
                    while (reader.BaseStream.Position != reader.BaseStream.Length)
                    {
                        buffer = reader.ReadBytes(bufferLength);
                        foreach (var item in buffer)
                        {
                            builder.Append(((char)item).ToString());
                        }

                        //Console.ReadKey();
                    }

                }

            }

            byte[] filedata = System.IO.File.ReadAllBytes(db.ObtenerArchivo().FullName);
            List<int> compreso = algoritmo.Compresion(builder.ToString());

            List<char> bytecompress = new List<char>();

            foreach (int  numero in compreso)
            {
                bytecompress.Add((char)numero);
            }

            ////////
            var ruta = Server.MapPath("~/DownloadedFiles/") + db.ObtenerArchivo().Name.Split('.')[0]+".lzw";
            using (StreamWriter outputFile= new StreamWriter(ruta))
            {
                foreach (char caracter in bytecompress)
                {
                    outputFile.Write(caracter.ToString());
                }
            }

            db.GuardarArchivo(new FileInfo(ruta));
        }


        //DESCOMPRESION DE ARCHIVO
        [HttpGet]
        public ActionResult DecompressFile()
        {
            return View();
        }
        //DESCOMPRESION DE ARCHIVO 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DecompressFile(HttpPostedFileBase File)
        {
            string filePath = string.Empty;
            if (File != null)
            {
                string path = Server.MapPath("~/UploadedFiles/");
                filePath = path + Path.GetFileName(File.FileName);
                string extension = Path.GetExtension(File.FileName);
                File.SaveAs(filePath);
                ViewBag.Message = "Archivo Cargado";

                FileInfo fileInfo = new FileInfo(filePath);

                string nombre_original = fileInfo.Name;
                long tamanio_original = fileInfo.Length;

                db.GuardarArchivo(fileInfo);
                GenerarArchivoDescomprimido();
                //db.GuardarArchivo(fileInfo);
                //DownloadFile(fileInfo);

                return RedirectToAction("DownloadFile");
            }

            return View();
        }

        public void GenerarArchivoDescomprimido()
        {
            const int bufferLength = 100;
            List<int> bytedecompress = new List<int>();

            var buffer = new char[bufferLength];
            using (var file = new FileStream(db.ObtenerArchivo().FullName, FileMode.Open))
            {
                using (var reader = new BinaryReader(file))
                {
                    while (reader.BaseStream.Position != reader.BaseStream.Length)
                    {
                        buffer = reader.ReadChars(bufferLength);
                        foreach (var item in buffer)
                        {
                            //Console.Write((char)item);
                            bytedecompress.Add((int)Convert.ToChar(item));
                        }

                        //Console.ReadKey();
                    }

                }

            }


            StringBuilder builder = new StringBuilder(algoritmo.Descompresion(bytedecompress));

            ////////
            var ruta = Server.MapPath("~/DownloadedFiles/") + db.ObtenerArchivo().Name.Split('.')[0]+".txt";
            using (StreamWriter outputFile= new StreamWriter(ruta))
            {
                outputFile.Write(builder);
            }

            db.GuardarArchivo(new FileInfo(ruta));
        }

        //METODO PARA DESCARGAR EL ARCHIVO
        public ActionResult DownloadFile()
        {
            return View();
        }

        //DESCARGAR EL ARCHIVO
        public FileResult Download()
        {
            
            var ruta = Server.MapPath("~/DownloadedFiles/")+ db.ObtenerArchivo().Name;
            return File(ruta, "text/plain", db.ObtenerArchivo().Name);
        }
    }
}

ED2_Lab1/ED2_Lab1/Views/LZW/CompressFile.cshtml
@{
    ViewBag.Title = "CompressFile";

}
<h2>UploadFile</h2>
@using (Html.BeginForm("CompressFile",
                        "LZW",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    <label for="file">Cargar Archivo:</label>
    <input type="file" name="file" id="file" /><br><br>
    <input type="submit" value="Cargar Archivo" />
    <br><br>
    @ViewBag.Message
}

ED2_Lab1/ED2_Lab1/Views/LZW/DecompressFile.cshtml
@{
    ViewBag.Title = "DecompressFile";

}
<h2>UploadFile</h2>
@using (Html.BeginForm("DecompressFile",
                        "LZW",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    <label for="file">Cargar Archivo:</label>
    <input type="file" name="file" id="file" /><br><br>
    <input type="submit" value="Cargar Archivo" />
    <br><br>
    @ViewBag.Message
}

ED2_Lab1/ED2_Lab1/Views/LZW/DownloadFile.cshtml
@{
    ViewBag.Title = "DownloadFile";
}

<h2>Descargar Archivo</h2>

<p>
    @Html.ActionLink("Download File", "Download") |
    @Html.ActionLink("Home LZW", "Index")
</p>

ED2_Lab1/ED2_Lab1/Views/LZW/Index.cshtml
@model IEnumerable<ED2_Lab1.Models.Archivo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Compresion LZW", "CompressFile") |
    @Html.ActionLink("Descompresion LZW", "DecompressFile")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombreArchivo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaCompresion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.razon_compresion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.factor_compresion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.porcentaje_reduccion)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombreArchivo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaCompresion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.razon_compresion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.factor_compresion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.porcentaje_reduccion)
        </td>
    </tr>
    }

</table>